# Generated by Django 5.2.11 on 2026-02-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListaExercicios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('arquivo', models.FileField(upload_to='listas/')),
                ('materia', models.CharField(max_length=100)),
                ('professor', models.CharField(max_length=100)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
